Work around a breaking change in GNU make 4.3
Apply https://salsa.debian.org/varnish-team/varnish/-/commit/3859ed3d232066245656f4d9289f23ac711c7818
to fix error "include vdef.h before vrt.h" in override_dh_gencontrol:

 make[1]: Entering directory '/<<PKGBUILDDIR>>'
 In file included from <stdin>:1:
 include/vrt.h:44:4: error: #error "include vdef.h before vrt.h"
    44 | #  error "include vdef.h before vrt.h"
       |    ^~~~~

Bug: T260702
Change-Id: Id95dbd35e17536f179bdf5d04a54ab8b49a1159b